// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RpsGame_WithDb;

namespace RpsGame_NoDb.Migrations
{
    [DbContext(typeof(RpsDbContext))]
    partial class RpsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("RpsGame_WithDb.Match", b =>
                {
                    b.Property<Guid>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("P1RoundWins")
                        .HasColumnType("int");

                    b.Property<int>("P2RoundWins")
                        .HasColumnType("int");

                    b.Property<Guid?>("Player1PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Player2PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Ties")
                        .HasColumnType("int");

                    b.HasKey("MatchId");

                    b.HasIndex("Player1PlayerId");

                    b.HasIndex("Player2PlayerId");

                    b.ToTable("matches");
                });

            modelBuilder.Entity("RpsGame_WithDb.Player", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Fname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumLosses")
                        .HasColumnType("int");

                    b.Property<int>("NumWins")
                        .HasColumnType("int");

                    b.HasKey("PlayerId");

                    b.ToTable("players");
                });

            modelBuilder.Entity("RpsGame_WithDb.Round", b =>
                {
                    b.Property<Guid>("RoundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Player1Choice")
                        .HasColumnType("int");

                    b.Property<int>("Player2Choice")
                        .HasColumnType("int");

                    b.Property<Guid?>("WinningPlayerPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoundId");

                    b.HasIndex("WinningPlayerPlayerId");

                    b.ToTable("rounds");
                });

            modelBuilder.Entity("RpsGame_WithDb.Match", b =>
                {
                    b.HasOne("RpsGame_WithDb.Player", "Player1")
                        .WithMany()
                        .HasForeignKey("Player1PlayerId");

                    b.HasOne("RpsGame_WithDb.Player", "Player2")
                        .WithMany()
                        .HasForeignKey("Player2PlayerId");

                    b.Navigation("Player1");

                    b.Navigation("Player2");
                });

            modelBuilder.Entity("RpsGame_WithDb.Round", b =>
                {
                    b.HasOne("RpsGame_WithDb.Player", "WinningPlayer")
                        .WithMany()
                        .HasForeignKey("WinningPlayerPlayerId");

                    b.Navigation("WinningPlayer");
                });
#pragma warning restore 612, 618
        }
    }
}
